name = "tour"
version = "1.0.0"
target = "javascript"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 0.32"
simplifile = ">= 2.0.0 and < 3.0.0"
snag = "~> 0.2"
htmb = ">= 2.0.0 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
